from typing import List, Dict, Any
from src.query import RAGQuery

class SkillBuilder:
    """
    Automates generating a comprehensive 'skill.md' reference text
    by querying the RAG system across predefined domain concepts.
    """
    
    # Predefined query groups covering core domain entities
    QUERY_GROUPS = {
        "1. 碳費徵收機制 (Carbon Fee Mechanism)": [
            "哪些事業需要繳交碳費？",
            "碳費的一般費率是多少？",
            "優惠費率A和B分別是多少？",
        ],
        "2. 自主減量計畫與優惠費率 (Autonomous Reduction Plans & Discounts)": [
            "什麼是自主減量計畫？",
            "轉換低碳燃料的措施有哪些？",
            "何時申請自主減量計畫可以適用優惠費率？",
            "執行自主減量計畫若因天災未能如期完成該怎麼辦？",
        ],
        "3. 歐盟 CBAM 規範 (EU CBAM Regulation)": [
            "What is the EU CBAM regulation and who does it apply to?",
            "How are CBAM certificates calculated?",
        ],
        "4. 溫室氣體清冊 (GHG Inventory)": [
            "目前台灣國家溫室氣體清冊由哪個單位統籌辦理？",
        ]
    }
    
    def __init__(self, query_engine: RAGQuery):
        """
        Initializes the SkillBuilder with a connected RAGQuery engine.
        """
        self.query_engine = query_engine
        
    def build_skill_content(self, n_results: int = 3, use_mock: bool = False) -> str:
        """
        Runs through all predefined query groups, queries the LLM, and 
        constructs a markdown report.
        
        Args:
            n_results: Number of chunks to retrieve per question.
            use_mock: If True, uses the mock LLM bypass.
            
        Returns:
            The generated markdown string.
        """
        lines = []
        lines.append("# Taiwan Carbon Market RAG - Domain Skill Reference\n")
        lines.append("This document was auto-generated by querying the RAG system "
                     "to extract foundational domain knowledge.\n")
        
        for category, questions in self.QUERY_GROUPS.items():
            lines.append(f"## {category}\n")
            
            for q in questions:
                lines.append(f"### Q: {q}\n")
                
                # Query the RAG system
                result = self.query_engine.query(
                    question=q, 
                    n_results=n_results, 
                    use_mock=use_mock
                )
                
                answer = result["answer"]
                sources = result["sources"]
                
                lines.append(f"**A:** {answer}\n")
                
                # Append citations
                if sources:
                    lines.append("*Citations:*")
                    for s in sources:
                        filename = s.get('filename', 'Unknown')
                        article = s.get('article', 'Unknown')
                        lines.append(f"- `{filename} -> {article}`")
                
                lines.append("\n---\n")
                
        return "\n".join(lines)
